language: node_js
node_js:
  - "0.12"
  - "iojs-2"
  - "iojs-3"
script:
  - npm test
  - npm run test-zuul
sudo: false
matrix:
  # dont run zuul tests for iojs
  exclude:
    - node_js: "iojs-2"
      script: npm test-zuul
    - node_js: "iojs-3"
      script: npm test-zuul
