ui: tape
browsers:
  - name: ie
    version: [9, 10, 11]
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: opera
    version: [11, 12]
  - name: safari
    version: latest
  - name: iphone
    version: [8.0, 9.0]
  - name: android
    version: latest
browserify:
  - transform: coffeeify
